apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: t846weezi-python-gitops
  description: This is GitOps manifest for t846weezi-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=t846weezi-python
    backstage.io/kubernetes-id: t846weezi-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: t846weezi-python
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:t846weezi-python
