apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: t846weezi-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: t846weezi-python 
  name: t846weezi-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: t846weezi-python 
